version: "3.7"
services:
  mongodb:
    container_name: mongodb
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017

  influxdb:
    container_name: influxdb
    image: influxdb:1.8
    restart: always
    ports:
      - '8086:8086'
    environment:
      INFLUXDB_DB: app

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./src/main/resources/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/etc/grafana/provisioning
    user: "472"